-- SQLite
--DROP TABLE Experience;
--DROP TABLE Education;
--DROP TABLE ScolarshipsAwardsVolunteering;
--DROP TABLE Projects;
--DROP TABLE Skills;
CREATE TABLE Experience (ID INTEGER PRIMARY KEY AUTOINCREMENT, company TINYTEXT, title TINYTEXT, date_start DATE, date_finish DATE, location TINYTEXT, description TEXT(65535), display TINYINT DEFAULT 3);
CREATE TABLE Education (ID INTEGER PRIMARY KEY AUTOINCREMENT, provider TINYTEXT, topic TINYTEXT, date_start DATE, date_finish DATE, grade TINYTEXT, description TEXT(65535), display TINYINT DEFAULT 3);
CREATE TABLE ScolarshipsAwardsVolunteering (ID INTEGER PRIMARY KEY AUTOINCREMENT, title TINYTEXT, date TINYTEXT, type TINYTEXT, description TEXT(65535), display TINYINT DEFAULT 3);
CREATE TABLE Projects (ID INTEGER PRIMARY KEY AUTOINCREMENT, title TINYTEXT, image TINYTEXT, link TINYTEXT, tags TINYTEXT, date_start DATE, date_finish DATE, short TEXT(65535), detail_type TINYTEXT, detail MEDIUMTEXT, display TINYINT DEFAULT 3);
CREATE TABLE Skills (ID INTEGER PRIMARY KEY AUTOINCREMENT, skill TINYTEXT, type TINYTEXT, display TINYINT DEFAULT 3);
CREATE TABLE Evidence (ID INTEGER PRIMARY KEY AUTOINCREMENT, skill_ID INTEGER, Evidence_ID INTEGER, Evidence_Table TINYTEXT, display TINYINT DEFAULT 3);